controller_manager_ns: pr2_controller_manager
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
#    action_ns: joint_trajectory_action
    default: true
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - flange


